project:
  type: website
  output-dir: docs

website:
  title: "deep learning"
  navbar:
    left:
      - href: index.qmd
        text: Projects
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



